Statments and Syntax home work
oleksandrklymko/LaSEP pull request #2
Opened 2020-10-15 11:31 UTC by oleksandrklymko

home work

2020-10-16 07:48 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +
Please, write two variants of such tasks:
- with additional functions
- only using loops.

2020-10-16 07:48 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +
Please, write two variants of such tasks:
- with additional functions
- only using loops.

2020-10-16 07:49 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +
Please, write two variants of such tasks:
- with additional functions
- only using loops.

2020-10-16 08:02 UTC, OlenaOhranchuk reviewed
General notes:
- Give an example on function call
- Check whether all code branches return the value
- In case of task concerns an array please, write two variants of such tasks:
  1. with additional functions
  2. only using loops.

2020-10-19 07:21 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +        return numbers[0] == 7 and numbers[-1] == 7
Make 7 as a variable and than use this variable.
Not all code branches return the result.

2020-10-19 07:21 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +        return numbers[0] == numbers[-1]
Not all code branches return the result.

2020-10-19 07:23 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    print(f'Original array:\n{numbers}')
```number_of_elements``` sounds like an array is expected to be passed into function.

2020-10-19 07:32 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +        return numbers1[0] == numbers2[0] or numbers1[-1] == numbers2[-1]
Not all code branches return the result.

2020-10-19 07:43 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    return numbers[1:] + numbers[:1]
Please rewrite this task so that function takes number of rotated elements as an argument. Do it to ways - with loop and without

2020-10-19 07:45 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    return numbers[::-1]
Please implement this tasks using loop.

2020-10-19 07:59 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    return numbers1 + numbers2
Please implement this task using loop.

2020-10-19 08:03 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    return max(numbers) - min(numbers)
Please implement this task not using ```max``` and ```min``` functions

2020-10-19 08:11 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    numbers.sort()
This row has changed input argument. So after call ```compute_avg``` the ```[50, 30, 50, 10, 20, 30]``` will look like ```[10, 20, 30, 30, 50, 50]```. Functions shouldn't change input arguments if they are not meant for this

2020-10-19 08:16 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +print(compute_sum([10, 20, 30, 17]))
For this array ```[10, 20, 30, 17]``` function should return ```60```. Please read the task more carefully.

2020-10-19 09:22 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 22. Write a Python program to check whether every element is a 3 or a 5 in a given array of integers.
This task should work for array [5, 3, 3, 5, 3] as well.

2020-10-19 09:28 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# A value is "everywhere" in an array if it presents for every pair of adjacent elements in the array.
Please rewrite this task so it works for ```[3, 1, 1, 3]```

2020-10-19 09:38 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +print(contains_numbers([1, 2, 3, 3, 4]))
Try to call this function for array ```[1, 2, 3, 4, 5]```

2020-10-19 09:41 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +
Try to call this function for array ```[2, 2, 6]```

2020-10-19 09:45 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 27. Write a Python program to convert an array into an index hash.
Please rewrite this task so it returns ```{5: 0, 2: 1, 3: 2, 8: 3, 5: 4, 6: 5}``` for an array ```[5, 2, 3, 8, 5, 6]```

2020-10-19 09:46 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    return {k: numbers.count(k) for k in numbers}
This function should return only one number not a hash.

2020-10-19 09:48 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 29. Write a Python program to check whether all items are identical in a given array.
Please make another variant of this task not using ```set```, but analyzing an array with a loop.

2020-10-19 09:58 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 35. Convert the array so that the first go all negative elements, and then positive (0 is considered positive)
This task is not about sorting elements, but just analyzing whether element is negative or positive.

2020-10-19 10:26 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +print(swap_columns([[1, 2, 3], [4, 5, 6]], 1))
Check how this function works for 4x5 array.

2020-10-19 10:30 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 40. Given the single-mass array. Cyclically shift the array on the K elements, on the right or left side.
Please do this task manually.

2020-10-20 06:51 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +    return sorted_numbers[-1] - sorted_numbers[0]
I can't see comparison with max value of the array in this function.
This function is very ineffective. Please analyze and describe the reason.

2020-10-20 07:16 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 24. Write a Python program to check whether a given array contains a 3 next to a 3 or a 5 next to a 5, but not both.
This function should work for array ```[1, 2, 3, 4, 5, 6, 7, 5, 5]```

2020-10-20 08:41 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# or there are two 6's separated by one element, such as [6, 2, 6].
This should work for arrays such ```[6, 2, 2, 6, 6]``` or ```[6, 2, 2, 6, 2, 6]```

2020-10-20 08:58 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +def convert_array(numbers):
Imagine that ```numbers``` consists of 1000.000 elements. Please describe pros and cons of implementation of this function.

2020-10-20 09:00 UTC, OlenaOhranchuk commented on StatmentsAndSyntax.py
> +# 37. In a two-dimensional array of order M and N, swap the specified columns.
Function should swap not only one element in each column, but the whole column.

2020-10-20 12:16 UTC, OlenaOhranchuk requested changes
A few comments

2020-10-21 10:17 UTC, oleksandrklymko commented on StatmentsAndSyntax.py
> +    return sorted_numbers[-1] - sorted_numbers[0]
This function is ineffective because there is no reason for sorting instead of sorting i needed simply find max and min value and operate with that data.

2020-10-21 17:27 UTC, oleksandrklymko commented on StatmentsAndSyntax.py
> +def convert_array(numbers):
It will take a lot of time going twice though all of this elements. And then pasting them into new list.

2020-10-22 08:03 UTC, OlenaOhranchuk approved these changes

2020-10-22 09:35 UTC, merged