Student
oleksandrklymko/LaSEP pull request #3
Opened 2020-10-25 11:27 UTC by oleksandrklymko

2020-10-30 09:17 UTC, OlenaOhranchuk commented on Student/group.py
> +class Group:
This class should be divided into two: one of them represents the single group and the second one maybe faculty (an array of groups).

2020-10-30 09:22 UTC, OlenaOhranchuk commented on Student/group.py
> +        if student in self.members:
```if student in self.members``` - this this condition is checked more than one time. And is expected it will be needed in other methods. It could be moved in the separate method.

2020-10-30 09:24 UTC, OlenaOhranchuk commented on Student/lecturer.py
> +        self.subject_name = subject_name
What is ```Lecturer``` can lead more than one subject?

2020-10-30 09:31 UTC, OlenaOhranchuk commented on Student/lecturer.py
> +    def rate_student(self, student, rate):
It is not the lecturer responsibility. This method should be in another class.

2020-10-30 09:33 UTC, OlenaOhranchuk commented on Student/lecturer.py
> +class Lecturer:
It would be great if ```Lecturer``` could grade a specific student.

2020-10-30 09:43 UTC, OlenaOhranchuk commented on Student/student.py
> +    students = []
This array doesn't not represent a single student.

2020-10-30 09:49 UTC, OlenaOhranchuk commented on Student/student.py
> +    def show_students_with_rating_from_x_to_y(cls, x, y):
This method is not connected to a single student.

2020-10-30 09:54 UTC, OlenaOhranchuk commented on Student/library.py
> +        for rented_book, date in student.rented_books:
Would it work if just check ```if book in student.rented_books``` ?

2020-10-30 09:55 UTC, OlenaOhranchuk commented on Student/room.py
> +class Room:
Change this class according to other comments.

2020-10-30 09:55 UTC, OlenaOhranchuk requested changes
Some classes should be changed.

2020-11-01 22:22 UTC, oleksandrklymko commented on Student/library.py
> +        for rented_book, date in student.rented_books:
No, because in self.rented_books it's array with tuples that store information like (book, data)

2020-11-02 07:00 UTC, OlenaOhranchuk commented on Student/faculty.py
> +                student.rating = sum(student.marks.values()) / len(student.marks)
The better solution would be
```
for student in group.members:
      calculate_rating(student)
def calculate_rating(self, student)
      student.rating = sum(student.marks.values()) / len(student.marks)
```

2020-11-02 07:11 UTC, OlenaOhranchuk commented on Student/lecturer.py
> +    def check_if_subject_in_subjects(self, subject):
This method should be private

2020-11-02 07:13 UTC, OlenaOhranchuk commented on Student/library.py
> +                books_that_not_returned_more_then_year = []
Name could be ```books_not_returned_more_then_year```

2020-11-02 07:17 UTC, OlenaOhranchuk commented on Student/main.py
> +nulp.add_student(alex)
More visible flow would be
```alex = nulp.create_student('Oleksandr', 'Klymko', 'Vasylovich', 1999, 'Zhovkva', 'Male')```

2020-11-02 07:21 UTC, OlenaOhranchuk approved these changes
Consider these comments in further development.

2022-07-21 08:37 UTC, closed without merging